#+author: Juho Hautala
#+title: Project I Report - Security flaws from OWASP top 10 list

* Security flaws from OWASP top 10 list

LINK: https://github.com/vastus/cybsec21-project1

FLAW 1:
https://github.com/vastus/cybsec21-project1/blob/master/project1/blog/views.py#L31
https://github.com/vastus/cybsec21-project1/blob/609cd90364be41e2b3df20bd72335be239bb46ae/project1/blog/views.py#L29

** Flaw 1: A03:2021 – Injection

The first flaw shows a SQL injection vulnerability.

The app in question is a blog. The different roles of users of the blog can be an admin, author, user, or guest. Guest is the only unauthenticated role meaning that guests do not or are not signed in to the web application.

For this flaw it doesn't matter if the user is authenticated or not. The injection flaw is vulnerable through the search functionality of the application. The search functionality can be accessed from any page of the app.

The flaw can be triggered for example in the following way:

1. go to the home page of the app
2. paste the following as the search query

```
%' and false union select 1337,email,1337,1337 from blog_user --
```

This will query the user table for the application and expose all the email addresses for each registered account. Changing the column name to any other column in the user table will expose its values. The SQL injection described in this flaw doesn't allow the execution of multiple statements but this vulnerability is a serious weakness since it can be used to expose all the data stored in the database.

See https://owasp.org/Top10/A03_2021-Injection/ for more

** Flaw 1: Fixing it

Instead of using raw SQL to perform the search one should use an ORM or escape the input used for the searching. Since this app is made with Django, the ORM should be used.

The fix can be seen in the following commit: https://github.com/vastus/cybsec21-project1/blob/7355ba0c02171a1833733d8dfd6e1706be61d637/project1/blog/views.py#L25.

FLAW 2:
exact source link pinpointing flaw 2...
description of flaw 2...
how to fix it...


