# Generated by Django 3.2.9 on 2021-11-26 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
